using System;
using System.Collections.Generic;
using System.Globalization;

namespace ImeBadge;

/// <summary>UI 언어. 설정 파일에는 이름 문자열("Auto")로 저장된다.</summary>
public enum UiLanguage { Auto, Korean, English }

/// <summary>
/// UI 문구 테이블(한국어·영어). resx 대신 코드 안의 사전을 쓴다. 트리밍·단일 파일 exe 에서 위성 어셈블리(satellite assembly)를
/// 신경 쓸 필요가 없고, 두 언어의 키가 같은지 단위 테스트로 검사할 수 있기 때문이다.
/// 비유하면 두 권의 사전을 나란히 놓고 같은 표제어를 찾는 것이다. 표제어가 한쪽에만 있으면 테스트가 잡는다.
/// 니모닉(&amp;)은 문구 안에 들어 있으므로 언어마다 겹치지 않게 골라야 한다.
/// </summary>
public static class Strings
{
    static UiLanguage _setting = UiLanguage.Auto;
    static bool _korean = DetectKorean();

    /// <summary>설정값. Auto 면 Windows 의 표시 언어(CurrentUICulture)가 한국어인지로 정한다.</summary>
    public static UiLanguage Setting
    {
        get => _setting;
        set
        {
            _setting = value;
            _korean = value switch { UiLanguage.Korean => true, UiLanguage.English => false, _ => DetectKorean() };
        }
    }

    public static bool IsKorean => _korean;

    /// <summary>현재 언어의 두 글자 코드("ko"/"en"). 진단 정보용.</summary>
    public static string Code => _korean ? "ko" : "en";

    static bool DetectKorean()
    {
        try { return CultureInfo.CurrentUICulture.TwoLetterISOLanguageName.Equals("ko", StringComparison.OrdinalIgnoreCase); }
        catch { return false; }
    }

    /// <summary>키에 해당하는 문구. 없는 키는 키 이름 그대로 돌려주어 눈에 띄게 한다(테스트가 먼저 잡는다).</summary>
    public static string Get(string key) =>
        (_korean ? Ko : En).TryGetValue(key, out var s) ? s : (_korean ? En : Ko).TryGetValue(key, out var t) ? t : key;

    public static string Format(string key, params object?[] args) => string.Format(CultureInfo.InvariantCulture, Get(key), args);

    /// <summary>테스트용: 한 언어의 전체 키·문구.</summary>
    public static IReadOnlyDictionary<string, string> Table(UiLanguage lang) => lang == UiLanguage.Korean ? Ko : En;

    static readonly Dictionary<string, string> Ko = new()
    {
        // ── 앱 ──
        ["app.name"] = "ImeBadge (한/영 배지)",
        ["app.tagline"] = "글자를 입력하기 전에 지금 한글인지 영문인지 알 수 있도록\n텍스트 커서 옆에 작은 배지를 띄워 줍니다.",
        ["app.firstRun"] = "커서 옆에 한/영 배지가 표시됩니다. 트레이 아이콘을 우클릭하면 모양과 동작을 바꿀 수 있습니다.",

        // ── 상태 ──
        ["state.paused"] = "일시 중지",
        ["state.hangul"] = "한글 입력",
        ["state.english"] = "영문 입력",
        ["state.englishCaps"] = "영문 입력 (Caps Lock)",
        ["state.hangulCaps"] = "한글 입력 (Caps Lock)",
        ["state.other"] = "다른 언어 입력",
        ["state.none"] = "입력 위치 없음",
        ["tray.resumeWith"] = " · {0} 로 재개",
        ["tray.pauseWith"] = " · {0} 일시 중지",

        // ── 트레이 메뉴 ──
        ["menu.current"] = "현재: {0}",
        ["menu.pause"] = "일시 중지(&P)",
        ["menu.settings"] = "설정(&S)...",
        ["menu.theme"] = "테마(&T)",
        ["menu.style"] = "모양(&M)",
        ["menu.style.basic"] = "기본",
        ["menu.style.characters"] = "캐릭터",
        ["menu.placement"] = "위치(&L)",
        ["menu.size"] = "크기(&Z)",
        ["menu.opacity"] = "불투명도(&O)",
        ["menu.autostart"] = "로그인 시 자동 시작(&A)",
        ["menu.checkUpdates"] = "업데이트 확인(&U)",
        ["menu.about"] = "정보(&I)...",
        ["menu.exit"] = "종료(&X)",
        ["menu.custom"] = "사용자 지정 ({0}%)",

        // ── 프리셋 ──
        ["style.box"] = "사각 배지",
        ["style.pill"] = "둥근 배지",
        ["style.dot"] = "점",
        ["style.underline"] = "밑줄",
        ["style.dotFlash"] = "점, 바뀔 때 1.5초 글자",
        ["style.cat"] = "고양이",
        ["style.dog"] = "강아지",
        ["style.heart"] = "하트",
        ["style.cloud"] = "구름",
        ["style.star"] = "별",
        ["theme.classic"] = "클래식",
        ["theme.blossom"] = "벚꽃",
        ["theme.candy"] = "캔디",
        ["theme.mint"] = "민트초코",
        ["theme.midnight"] = "미드나잇",
        ["place.aboveRight"] = "커서 오른쪽 위",
        ["place.belowRight"] = "커서 오른쪽 아래",
        ["place.aboveLeft"] = "커서 왼쪽 위",
        ["place.belowLeft"] = "커서 왼쪽 아래",
        ["size.small"] = "작게 (80%)",
        ["size.normal"] = "보통 (100%)",
        ["size.large"] = "크게 (130%)",
        ["size.xlarge"] = "아주 크게 (160%)",
        ["opacity.100"] = "불투명 (100%)",
        ["opacity.85"] = "살짝 비침 (85%)",
        ["opacity.70"] = "반투명 (70%)",
        ["opacity.50"] = "많이 비침 (50%)",
        ["language.auto"] = "시스템 언어 (자동)",
        ["language.ko"] = "한국어",
        ["language.en"] = "English",

        // ── 설정 창 ──
        ["settings.title"] = "{0} 설정",
        ["settings.ok"] = "확인",
        ["settings.cancel"] = "취소",
        ["settings.reset"] = "기본값 복원(&R)",
        ["group.look"] = "모양",
        ["group.behavior"] = "동작",
        ["group.preview"] = "미리보기",
        ["group.exclude"] = "배지를 띄우지 않을 앱",
        ["look.style"] = "배지 모양(&M)",
        ["look.placement"] = "위치(&L)",
        ["look.placement.tip"] = "위쪽은 다음 줄 글자를 덜 가립니다. 화면 가장자리라 자리가 없으면 반대쪽으로 옮깁니다.",
        ["look.size"] = "크기(&Z)",
        ["look.size.tip"] = "모니터 DPI 배율에 추가로 곱해집니다.",
        ["look.opacity"] = "불투명도(&O)",
        ["look.opacity.tip"] = "배지 배경만 비치고 글자는 또렷하게 유지됩니다.",
        ["look.hangulColor"] = "한글 배지 색(&H)",
        ["look.englishColor"] = "영문 배지 색(&E)",
        ["look.color.tip"] = "글자색(흰/검)은 고른 색의 밝기에 맞춰 자동으로 정해집니다.",
        ["look.animate"] = "나타날 때 서서히, 바뀔 때 살짝 커지는 효과(&N)",
        ["look.animate.tip"] = "Windows 설정 → 접근성 → 시각 효과 → 애니메이션 효과가 꺼져 있으면 여기와 상관없이 생략합니다.",
        ["look.capsLock"] = "배지에 Caps Lock 표시  (한 → 꺆, a → A)(&C)",
        ["look.capsLock.tip"] = "켜면 영문 배지가 평소 a, Caps Lock 이 켜지면 A 로 바뀌고, 한글 배지는 한 → 꺆 으로 바뀝니다. Caps Lock 이 켜져 있으면 글자 아래에 밑줄도 긋습니다. 트레이 아이콘과 점·밑줄 모양은 그대로입니다. 끄면 항상 한 / A.",
        ["look.theme"] = "테마(&V)",
        ["look.theme.tip"] = "배지 색과 질감, 이 창의 색을 한 벌로 바꿉니다. 고른 뒤에도 아래에서 배지 색을 따로 바꿀 수 있습니다.",
        ["behavior.autostart"] = "Windows 로그인 시 자동 시작(&A)",
        ["behavior.fullscreen"] = "전체 화면 앱(게임·동영상)에서는 숨김(&F)",
        ["behavior.trayState"] = "트레이 아이콘에도 한/영 상태 표시(&T)",
        ["behavior.hotkey"] = "단축키로 일시 중지 켜기/끄기(&K)",
        ["behavior.hotkey.tip"] = "여기를 클릭한 뒤 원하는 키 조합을 누르세요. Ctrl, Alt, Win 중 하나가 들어가야 합니다.",
        ["behavior.hotkey.placeholder"] = "키 조합을 누르세요",
        ["behavior.updates"] = "새 버전이 나오면 알림 (하루 한 번 확인)(&U)",
        ["behavior.updates.tip"] = "GitHub Releases 에서 정식 버전만 확인합니다. 끄면 네트워크 접속이 전혀 없습니다.",
        ["behavior.poll"] = "확인 주기 (ms)(&I)",
        ["behavior.poll.note"] = "작을수록 빨리 반응하고 CPU 를 조금 더 씁니다. 기본 100.",
        ["behavior.poll.tip"] = "한/영 상태를 다시 읽는 간격입니다. 배지가 한동안 안 보이면 자동으로 3배 느려집니다.",
        ["behavior.language"] = "언어(&G)",
        ["behavior.language.tip"] = "설정 창·트레이 메뉴·알림의 언어입니다. 배지 글자(한/A)는 바뀌지 않습니다.",
        ["preview.tip"] = "왼쪽은 밝은 배경(메모장), 오른쪽은 어두운 배경(VS Code 등)에서의 모습입니다.\n배지가 옆줄 글자를 얼마나 가리는지, 불투명도를 낮추면 얼마나 비치는지도 볼 수 있습니다.",
        ["exclude.new.tip"] = "실행 중인 앱을 고르거나 실행 파일 이름을 직접 입력하세요. 끝에 * 를 붙이면 앞부분만 맞으면 됩니다.",
        ["exclude.add"] = "추가(&D)",
        ["exclude.remove"] = "삭제(&X)",
        ["exclude.note"] = "실행 파일 이름(.exe 생략 가능). 끝에 * 를 붙이면 앞부분만 맞으면 됩니다.\n예)  mstsc  /  vmware-vmx  /  Unreal*",
        ["group.corner"] = "커서를 못 찾는 앱 (창 모서리에 표시)",
        ["corner.add"] = "추가",
        ["corner.remove"] = "삭제",
        ["corner.note"] = "자체 커서를 그리는 앱(Xshell 같은 터미널)은 커서 위치를 알 수 없을 때가 있습니다. 이 목록의 앱은\n그럴 때 배지를 입력 창의 왼쪽 아래 모서리에 고정해 띄웁니다(위치 설정 무시). 예)  Xshell*",
        ["corner.trackImage"] = "화면을 분석해 커서를 따라가기 (실험적)",
        ["corner.trackImage.tip"] = "위 목록의 앱에서 창을 캡처해 깜빡이는 커서를 찾아 배지를 그 옆에 둡니다. 찾으면 커서를 따라가고, 화면 출력이 많아 못 찾으면 모서리에 고정합니다. CPU 를 조금 더 씁니다.",

        // ── 설정 창: 머리·카드 설명·타일 이름 ──
        ["settings.heading"] = "ImeBadge 설정",
        ["settings.subtitle"] = "바꾸는 즉시 커서 옆 배지에 반영됩니다. 확인을 누르면 저장되고, 취소하면 열 때의 설정으로 돌아갑니다.",
        ["group.look.desc"] = "배지의 생김새와 색. 오른쪽 미리보기와 실제 배지에 바로 반영됩니다.",
        ["group.behavior.desc"] = "언제 보여 주고 어떻게 다룰지.",
        ["group.preview.desc"] = "실제 렌더러가 그린 결과. 왼쪽은 밝은 편집기, 오른쪽은 어두운 편집기.",
        ["group.exclude.desc"] = "원격 데스크톱·가상 머신처럼 안에서 따로 배지를 쓰는 앱을 빼 둡니다.",
        ["group.corner.desc"] = "커서 위치를 알 수 없는 앱에서는 배지를 입력 창 왼쪽 아래 모서리에 고정합니다.",
        ["style.short.box"] = "사각",
        ["style.short.pill"] = "둥근",
        ["style.short.dot"] = "점",
        ["style.short.underline"] = "밑줄",
        ["style.short.dotFlash"] = "점+글자",
        ["place.short.aboveRight"] = "오른쪽 위",
        ["place.short.belowRight"] = "오른쪽 아래",
        ["place.short.aboveLeft"] = "왼쪽 위",
        ["place.short.belowLeft"] = "왼쪽 아래",
        ["look.swatch.tip"] = "견본은 고른 테마에 맞춘 색이고, 마지막 견본은 사용자 지정 색입니다. 글자색은 고른 색의 밝기에 맞춰 자동으로 정해집니다.",
        ["preview.light"] = "밝은 배경",
        ["preview.dark"] = "어두운 배경",
        ["about.license"] = "Apache License 2.0 · 개인정보를 수집하지 않습니다",

        // ── 정보 창 ──
        ["about.title"] = "{0} 정보",
        ["about.version"] = "버전 {0}",
        ["about.checkUpdates"] = "새 버전 확인",
        ["about.repo"] = "GitHub 저장소 열기",
        ["about.releases"] = "릴리스(다운로드) 페이지 열기",
        ["about.settingsDir"] = "설정 폴더 열기",
        ["about.logDir"] = "로그 폴더 열기",
        ["about.copyDiag"] = "진단 정보 복사 (이슈 신고용)",
        ["about.copied"] = "{0} — 복사했습니다",
        ["about.close"] = "닫기",
        ["diag.dpi"] = "DPI: {0} ({1}%), 모니터 {2}대",
        ["diag.theme"] = "테마: {0}{1}, 애니메이션 효과: {2}, UI 언어: {3}",
        ["diag.dark"] = "어둡게",
        ["diag.light"] = "밝게",
        ["diag.highContrast"] = ", 고대비",
        ["diag.on"] = "켜짐",
        ["diag.off"] = "꺼짐",
        ["diag.settings"] = "설정: 모양={0}, 위치={1}, 크기={2}%, 불투명도={3}%, 주기={4}ms, 단축키={5}, 제외 앱={6}개",
        ["diag.exe"] = "실행 파일: {0}",
        ["diag.settingsFile"] = "설정 파일: {0}",
        ["diag.logDir"] = "로그 폴더: {0}",
        ["diag.unknown"] = "(알 수 없음)",

        // ── 대화상자 ──
        ["dialog.details"] = "자세히",
        ["dialog.brief"] = "간단히",
        ["dialog.openLogDir"] = "로그 폴더 열기",
        ["dialog.close"] = "닫기",
        ["dialog.yesPrefix"] = "[예] {0}",
        ["crash.heading"] = "{0}에 문제가 생겨 종료합니다.",
        ["crash.text"] = "자세한 내용은 로그 폴더의 errors.log 에 기록되어 있습니다. 문제가 반복되면 이 파일과 함께 이슈로 알려 주세요.",
        ["hotkey.failed"] = "단축키 {0} 을(를) 등록하지 못했습니다.",
        ["hotkey.failed.text"] = "다른 프로그램이 같은 조합을 쓰고 있을 수 있습니다. 설정에서 다른 조합을 고르세요.",
        ["autostart.failed"] = "자동 시작 설정을 바꾸지 못했습니다.",
        ["autostart.failed.text"] = "로그 폴더의 errors.log 에 원인이 기록되어 있습니다. (트레이 메뉴 → 정보 → 로그 폴더 열기)",

        // ── 업데이트 ──
        ["update.balloon.title"] = "새 버전이 있습니다",
        ["update.balloon.text"] = "{0} {1} 을(를) 받을 수 있습니다. (현재 {2})\n클릭하면 업데이트 창이 열립니다.",
        ["update.none"] = "아직 정식 릴리스가 없습니다.",
        ["update.latest"] = "최신 버전을 쓰고 있습니다.",
        ["update.current"] = "현재 {0}",
        ["update.currentLatest"] = "현재 {0}, 최신 {1}",
        ["update.failed"] = "업데이트 정보를 가져오지 못했습니다.",
        ["update.failed.text"] = "네트워크 연결을 확인한 뒤 다시 시도하세요.",
        ["update.offer.heading"] = "새 버전 {0} 이(가) 있습니다.",
        ["update.offer.text"] = "현재 {0} 을(를) 쓰고 있습니다.",
        ["update.open"] = "다운로드 페이지 열기",
        ["update.open.note"] = "브라우저에서 릴리스 페이지를 엽니다.",
        ["update.later"] = "나중에",
        ["update.later.note"] = "다음에 다시 알립니다.",
        ["update.skip"] = "이 버전 건너뛰기",
        ["update.skip.note"] = "{0} 은(는) 자동으로 알리지 않습니다. 더 새 버전이 나오면 다시 알립니다.",
        ["update.upgrade"] = "지금 업그레이드",
        ["update.upgrade.note"] = "새 버전을 내려받아 적용하고 자동으로 다시 시작합니다.",
        ["update.progress.title"] = "업데이트 {0}",
        ["update.preparing"] = "준비하는 중...",
        ["update.downloading"] = "내려받는 중... {0} / {1} MB",
        ["update.downloading.unknown"] = "내려받는 중... {0} MB",
        ["update.verifying"] = "받은 파일을 확인하는 중...",
        ["update.applying"] = "적용하는 중... 잠시 뒤 새 버전으로 다시 시작합니다.",
        ["update.cancel"] = "취소",
        ["update.auto.failed"] = "자동 업그레이드를 마치지 못했습니다.",
        ["update.auto.failed.text"] = "다운로드 페이지에서 직접 받아 설치할 수 있습니다.",
        ["update.auto.noAsset"] = "이 릴리스에는 지금 쓰는 설치 형태({0})에 맞는 파일이 없습니다.",
        ["update.auto.noChecksum"] = "이 릴리스에 체크섬 목록(SHA256SUMS.txt)이 없어 받은 파일을 확인할 수 없습니다.",
        ["update.auto.checksum"] = "받은 파일이 손상되었습니다(체크섬이 맞지 않음).",
        ["update.apply.failed"] = "새 버전으로 바꾸지 못했습니다.",
        ["update.apply.failed.text"] = "프로그램 파일을 쓸 수 없었습니다. 예전 버전이 그대로 남아 있으니, 다운로드 페이지에서 받아 다시 설치해 주세요.",
    };

    static readonly Dictionary<string, string> En = new()
    {
        // ── App ──
        ["app.name"] = "ImeBadge (Korean/English badge)",
        ["app.tagline"] = "Shows a small badge next to the text caret so you know\nwhether you're typing Korean or English before you type.",
        ["app.firstRun"] = "A Korean/English badge now appears next to the caret. Right-click the tray icon to change its look and behavior.",

        // ── State ──
        ["state.paused"] = "Paused",
        ["state.hangul"] = "Korean",
        ["state.english"] = "English",
        ["state.englishCaps"] = "English (Caps Lock)",
        ["state.hangulCaps"] = "Korean (Caps Lock)",
        ["state.other"] = "Other language",
        ["state.none"] = "No text field",
        ["tray.resumeWith"] = " · {0} to resume",
        ["tray.pauseWith"] = " · {0} to pause",

        // ── Tray menu (mnemonics: P S H L Z O W U A X) ──
        ["menu.current"] = "Now: {0}",
        ["menu.pause"] = "&Pause",
        ["menu.settings"] = "&Settings...",
        ["menu.theme"] = "&Theme",
        ["menu.style"] = "S&hape",
        ["menu.style.basic"] = "Basic",
        ["menu.style.characters"] = "Characters",
        ["menu.placement"] = "&Location",
        ["menu.size"] = "Si&ze",
        ["menu.opacity"] = "&Opacity",
        ["menu.autostart"] = "Start with &Windows",
        ["menu.checkUpdates"] = "Check for &updates",
        ["menu.about"] = "&About...",
        ["menu.exit"] = "E&xit",
        ["menu.custom"] = "Custom ({0}%)",

        // ── Presets ──
        ["style.box"] = "Square badge",
        ["style.pill"] = "Rounded badge",
        ["style.dot"] = "Dot",
        ["style.underline"] = "Underline",
        ["style.dotFlash"] = "Dot, text for 1.5 s on change",
        ["style.cat"] = "Cat",
        ["style.dog"] = "Dog",
        ["style.heart"] = "Heart",
        ["style.cloud"] = "Cloud",
        ["style.star"] = "Star",
        ["theme.classic"] = "Classic",
        ["theme.blossom"] = "Blossom",
        ["theme.candy"] = "Candy",
        ["theme.mint"] = "Mint Choco",
        ["theme.midnight"] = "Midnight",
        ["place.aboveRight"] = "Above right of caret",
        ["place.belowRight"] = "Below right of caret",
        ["place.aboveLeft"] = "Above left of caret",
        ["place.belowLeft"] = "Below left of caret",
        ["size.small"] = "Small (80%)",
        ["size.normal"] = "Normal (100%)",
        ["size.large"] = "Large (130%)",
        ["size.xlarge"] = "Extra large (160%)",
        ["opacity.100"] = "Opaque (100%)",
        ["opacity.85"] = "Slightly see-through (85%)",
        ["opacity.70"] = "Translucent (70%)",
        ["opacity.50"] = "Mostly see-through (50%)",
        ["language.auto"] = "System language (auto)",
        ["language.ko"] = "한국어",
        ["language.en"] = "English",

        // ── Settings window (mnemonics: S L Z O K E N C W F T H U I G R D M) ──
        ["settings.title"] = "{0} Settings",
        ["settings.ok"] = "OK",
        ["settings.cancel"] = "Cancel",
        ["settings.reset"] = "&Reset to defaults",
        ["group.look"] = "Appearance",
        ["group.behavior"] = "Behavior",
        ["group.preview"] = "Preview",
        ["group.exclude"] = "Apps without the badge",
        ["look.style"] = "Badge &shape",
        ["look.placement"] = "&Location",
        ["look.placement.tip"] = "Above hides less of the next line. If there is no room at the screen edge, the badge moves to the other side.",
        ["look.size"] = "Si&ze",
        ["look.size.tip"] = "Multiplied on top of the monitor's DPI scaling.",
        ["look.opacity"] = "&Opacity",
        ["look.opacity.tip"] = "Only the badge background becomes see-through; the text stays crisp.",
        ["look.hangulColor"] = "&Korean badge color",
        ["look.englishColor"] = "&English badge color",
        ["look.color.tip"] = "Text color (white/black) is chosen automatically from the brightness of the color you pick.",
        ["look.animate"] = "Fade in when shown, pulse when the mode cha&nges",
        ["look.animate.tip"] = "Skipped regardless of this setting when Windows Settings → Accessibility → Visual effects → Animation effects is off.",
        ["look.capsLock"] = "Show &Caps Lock on the badge  (한 → 꺆, a → A)",
        ["look.capsLock.tip"] = "When on, the English badge reads a normally and A with Caps Lock on; the Korean badge changes from 한 to 꺆. With Caps Lock on, a bar is drawn under the letter as well. The tray icon and the dot and underline shapes stay the same. When off, always 한 / A.",
        ["look.theme"] = "&Visual theme",
        ["look.theme.tip"] = "Changes the badge colors, finish and this window's colors as a set. You can still pick badge colors below afterwards.",
        ["behavior.autostart"] = "Start with &Windows",
        ["behavior.fullscreen"] = "Hide in &fullscreen apps (games, videos)",
        ["behavior.trayState"] = "Show the mode on the &tray icon too",
        ["behavior.hotkey"] = "&Hotkey to pause/resume",
        ["behavior.hotkey.tip"] = "Click here, then press the key combination you want. It must include Ctrl, Alt or Win.",
        ["behavior.hotkey.placeholder"] = "Press a key combination",
        ["behavior.updates"] = "&Update notifications (checks once a day)",
        ["behavior.updates.tip"] = "Only stable releases on GitHub Releases are checked. When off, the app never touches the network.",
        ["behavior.poll"] = "Poll &interval (ms)",
        ["behavior.poll.note"] = "Lower reacts faster and uses a bit more CPU. Default 100.",
        ["behavior.poll.tip"] = "How often the mode is re-read. Slows down 3× automatically while the badge has been hidden for a while.",
        ["behavior.language"] = "Lan&guage",
        ["behavior.language.tip"] = "Language of the settings window, tray menu and notifications. The badge text (한/A) does not change.",
        ["preview.tip"] = "Left: on a light background (Notepad). Right: on a dark background (VS Code etc.).\nIt also shows how much of the neighboring line the badge covers, and how much shows through at lower opacity.",
        ["exclude.new.tip"] = "Pick a running app or type an executable name. A trailing * matches by prefix.",
        ["exclude.add"] = "A&dd",
        ["exclude.remove"] = "Re&move",
        ["exclude.note"] = "Executable name (.exe optional). A trailing * matches by prefix.\ne.g.  mstsc  /  vmware-vmx  /  Unreal*",
        ["group.corner"] = "Apps without a findable caret (corner badge)",
        ["corner.add"] = "Add",
        ["corner.remove"] = "Remove",
        ["corner.note"] = "Apps that draw their own cursor (terminals such as Xshell) may expose no caret position. For apps in this list\nthe badge is then pinned to the bottom-left corner of the focused window (placement setting ignored). e.g.  Xshell*",
        ["corner.trackImage"] = "Follow the cursor by analyzing the screen (experimental)",
        ["corner.trackImage.tip"] = "For the apps above, capture the window to locate the blinking cursor and place the badge beside it. When found the badge follows the cursor; when heavy output hides it, the badge falls back to the corner. Uses a little more CPU.",

        // ── Settings window: header, card descriptions, tile labels ──
        ["settings.heading"] = "ImeBadge Settings",
        ["settings.subtitle"] = "Changes apply to the badge immediately. OK saves them; Cancel restores the settings from when the window opened.",
        ["group.look.desc"] = "How the badge looks. Reflected in the preview and the real badge right away.",
        ["group.behavior.desc"] = "When to show it and how to control it.",
        ["group.preview.desc"] = "Drawn by the real renderer. Left: a light editor, right: a dark editor.",
        ["group.exclude.desc"] = "Leave out apps that show their own badge inside, such as Remote Desktop or virtual machines.",
        ["group.corner.desc"] = "When the caret position is unknown, pin the badge to the bottom-left corner of the focused window.",
        ["style.short.box"] = "Square",
        ["style.short.pill"] = "Rounded",
        ["style.short.dot"] = "Dot",
        ["style.short.underline"] = "Underline",
        ["style.short.dotFlash"] = "Dot+text",
        ["place.short.aboveRight"] = "Above right",
        ["place.short.belowRight"] = "Below right",
        ["place.short.aboveLeft"] = "Above left",
        ["place.short.belowLeft"] = "Below left",
        ["look.swatch.tip"] = "The swatches match the chosen theme; the last one is a custom color. The text color follows the brightness of the color you pick.",
        ["preview.light"] = "Light background",
        ["preview.dark"] = "Dark background",
        ["about.license"] = "Apache License 2.0 · No personal data is collected",

        // ── About window ──
        ["about.title"] = "About {0}",
        ["about.version"] = "Version {0}",
        ["about.checkUpdates"] = "Check for updates",
        ["about.repo"] = "Open GitHub repository",
        ["about.releases"] = "Open releases (download) page",
        ["about.settingsDir"] = "Open settings folder",
        ["about.logDir"] = "Open log folder",
        ["about.copyDiag"] = "Copy diagnostics (for bug reports)",
        ["about.copied"] = "{0} — copied",
        ["about.close"] = "Close",
        ["diag.dpi"] = "DPI: {0} ({1}%), {2} monitor(s)",
        ["diag.theme"] = "Theme: {0}{1}, animation effects: {2}, UI language: {3}",
        ["diag.dark"] = "dark",
        ["diag.light"] = "light",
        ["diag.highContrast"] = ", high contrast",
        ["diag.on"] = "on",
        ["diag.off"] = "off",
        ["diag.settings"] = "Settings: shape={0}, placement={1}, size={2}%, opacity={3}%, interval={4}ms, hotkey={5}, excluded apps={6}",
        ["diag.exe"] = "Executable: {0}",
        ["diag.settingsFile"] = "Settings file: {0}",
        ["diag.logDir"] = "Log folder: {0}",
        ["diag.unknown"] = "(unknown)",

        // ── Dialogs ──
        ["dialog.details"] = "Details",
        ["dialog.brief"] = "Less",
        ["dialog.openLogDir"] = "Open log folder",
        ["dialog.close"] = "Close",
        ["dialog.yesPrefix"] = "[Yes] {0}",
        ["crash.heading"] = "{0} ran into a problem and has to close.",
        ["crash.text"] = "Details are in errors.log in the log folder. If this keeps happening, please open an issue and attach that file.",
        ["hotkey.failed"] = "Could not register the hotkey {0}.",
        ["hotkey.failed.text"] = "Another program may be using the same combination. Pick a different one in Settings.",
        ["autostart.failed"] = "Could not change the startup setting.",
        ["autostart.failed.text"] = "The cause is recorded in errors.log in the log folder (tray menu → About → Open log folder).",

        // ── Updates ──
        ["update.balloon.title"] = "New version available",
        ["update.balloon.text"] = "{0} {1} is available (you have {2}).\nClick to open the update window.",
        ["update.none"] = "There is no stable release yet.",
        ["update.latest"] = "You're on the latest version.",
        ["update.current"] = "Current: {0}",
        ["update.currentLatest"] = "Current {0}, latest {1}",
        ["update.failed"] = "Could not fetch update information.",
        ["update.failed.text"] = "Check your network connection and try again.",
        ["update.offer.heading"] = "Version {0} is available.",
        ["update.offer.text"] = "You are using {0}.",
        ["update.open"] = "Open download page",
        ["update.open.note"] = "Opens the release page in your browser.",
        ["update.later"] = "Later",
        ["update.later.note"] = "Remind me next time.",
        ["update.skip"] = "Skip this version",
        ["update.skip.note"] = "{0} won't be announced again. You'll be notified when a newer version is out.",
        ["update.upgrade"] = "Upgrade now",
        ["update.upgrade.note"] = "Downloads the new version, applies it and restarts automatically.",
        ["update.progress.title"] = "Update {0}",
        ["update.preparing"] = "Preparing...",
        ["update.downloading"] = "Downloading... {0} / {1} MB",
        ["update.downloading.unknown"] = "Downloading... {0} MB",
        ["update.verifying"] = "Verifying the download...",
        ["update.applying"] = "Applying... the new version will start in a moment.",
        ["update.cancel"] = "Cancel",
        ["update.auto.failed"] = "The automatic upgrade could not be completed.",
        ["update.auto.failed.text"] = "You can download and install the new version yourself.",
        ["update.auto.noAsset"] = "This release has no file for the way this copy was installed ({0}).",
        ["update.auto.noChecksum"] = "This release has no checksum list (SHA256SUMS.txt), so the download cannot be verified.",
        ["update.auto.checksum"] = "The downloaded file is corrupt (checksum mismatch).",
        ["update.apply.failed"] = "Could not switch to the new version.",
        ["update.apply.failed.text"] = "The program file could not be written. Your current version is untouched - please download and install the new version manually.",
    };
}
