using System;
using System.Collections.Generic;
using System.Globalization;

namespace ImeBadge;

/// <summary>UI 언어. 설정 파일에는 이름 문자열("Auto")로 저장된다.</summary>
public enum UiLanguage { Auto, Korean, English }

/// <summary>
/// UI 문구 테이블(한국어·영어). resx 대신 코드 안의 사전을 쓴다. 트리밍·단일 파일 exe 에서 위성 어셈블리(satellite assembly)를
/// 신경 쓸 필요가 없고, 두 언어의 키가 같은지 단위 테스트로 검사할 수 있기 때문이다.
/// 비유하면 두 권의 사전을 나란히 놓고 같은 표제어를 찾는 것이다. 표제어가 한쪽에만 있으면 테스트가 잡는다.
/// 니모닉(&amp;)은 문구 안에 들어 있으므로 언어마다 겹치지 않게 골라야 한다.
/// </summary>
public static class Strings
{
    static UiLanguage _setting = UiLanguage.Auto;
    static bool _korean = DetectKorean();

    /// <summary>설정값. Auto 면 Windows 의 표시 언어(CurrentUICulture)가 한국어인지로 정한다.</summary>
    public static UiLanguage Setting
    {
        get => _setting;
        set
        {
            _setting = value;
            _korean = value switch { UiLanguage.Korean => true, UiLanguage.English => false, _ => DetectKorean() };
        }
    }

    public static bool IsKorean => _korean;

    /// <summary>현재 언어의 두 글자 코드("ko"/"en"). 진단 정보용.</summary>
    public static string Code => _korean ? "ko" : "en";

    static bool DetectKorean()
    {
        try { return CultureInfo.CurrentUICulture.TwoLetterISOLanguageName.Equals("ko", StringComparison.OrdinalIgnoreCase); }
        catch { return false; }
    }

    /// <summary>키에 해당하는 문구. 없는 키는 키 이름 그대로 돌려주어 눈에 띄게 한다(테스트가 먼저 잡는다).</summary>
    public static string Get(string key) =>
        (_korean ? Ko : En).TryGetValue(key, out var s) ? s : (_korean ? En : Ko).TryGetValue(key, out var t) ? t : key;

    public static string Format(string key, params object?[] args) => string.Format(CultureInfo.InvariantCulture, Get(key), args);

    /// <summary>테스트용: 한 언어의 전체 키·문구.</summary>
    public static IReadOnlyDictionary<string, string> Table(UiLanguage lang) => lang == UiLanguage.Korean ? Ko : En;

    static readonly Dictionary<string, string> Ko = new()
    {
        // ── 앱 ──
        ["app.name"] = "ImeBadge (한/영 배지)",
        ["app.tagline"] = "글자를 입력하기 전에 지금 한글인지 영문인지 알 수 있도록\n텍스트 커서 옆에 작은 배지를 띄워 줍니다.",
        ["app.firstRun"] = "커서 옆에 한/영 배지가 표시됩니다. 트레이 아이콘을 우클릭하면 모양과 동작을 바꿀 수 있습니다.",

        // ── 상태 ──
        ["state.paused"] = "일시 중지",
        ["state.hangul"] = "한글 입력",
        ["state.english"] = "영문 입력",
        ["state.englishCaps"] = "영문 입력 (Caps Lock)",
        ["state.hangulCaps"] = "한글 입력 (Caps Lock)",
        ["state.other"] = "다른 언어 입력",
        ["state.none"] = "입력 위치 없음",
        ["state.overtype"] = "{0} · 겹쳐 쓰기",
        ["tray.resumeWith"] = " · {0} 로 재개",
        ["tray.pauseWith"] = " · {0} 일시 중지",

        // ── 트레이 메뉴 ──
        ["menu.current"] = "현재: {0}",
        ["menu.pause"] = "일시 중지(&P)",
        ["menu.settings"] = "설정(&S)...",
        ["menu.theme"] = "테마(&T)",
        ["menu.style"] = "모양(&M)",
        ["menu.style.basic"] = "기본",
        ["menu.style.characters"] = "캐릭터",
        ["menu.placement"] = "위치(&L)",
        ["menu.size"] = "크기(&Z)",
        ["menu.opacity"] = "불투명도(&O)",
        ["menu.autostart"] = "로그인 시 자동 시작(&A)",
        ["menu.checkUpdates"] = "업데이트 확인(&U)",
        ["menu.about"] = "정보(&I)...",
        ["menu.exit"] = "종료(&X)",
        ["menu.custom"] = "사용자 지정 ({0}%)",

        // ── 프리셋 ──
        ["style.box"] = "사각 배지",
        ["style.pill"] = "둥근 배지",
        ["style.dot"] = "점",
        ["style.underline"] = "밑줄",
        ["style.dotFlash"] = "점, 바뀔 때 1.5초 글자",
        ["style.cat"] = "고양이",
        ["style.dog"] = "강아지",
        ["style.heart"] = "하트",
        ["style.cloud"] = "구름",
        ["style.star"] = "별",
        ["theme.classic"] = "클래식",
        ["theme.blossom"] = "벚꽃",
        ["theme.candy"] = "캔디",
        ["theme.mint"] = "민트초코",
        ["theme.midnight"] = "미드나잇",
        ["place.aboveRight"] = "커서 오른쪽 위",
        ["place.belowRight"] = "커서 오른쪽 아래",
        ["place.aboveLeft"] = "커서 왼쪽 위",
        ["place.belowLeft"] = "커서 왼쪽 아래",
        ["place.above"] = "커서 위",
        ["place.below"] = "커서 아래",
        ["size.small"] = "작게 (80%)",
        ["size.normal"] = "보통 (100%)",
        ["size.large"] = "크게 (130%)",
        ["size.xlarge"] = "아주 크게 (160%)",
        ["opacity.100"] = "불투명 (100%)",
        ["opacity.85"] = "살짝 비침 (85%)",
        ["opacity.70"] = "반투명 (70%)",
        ["opacity.50"] = "많이 비침 (50%)",
        ["language.auto"] = "시스템 언어 (자동)",
        ["language.ko"] = "한국어",
        ["language.en"] = "English",

        // ── 설정 창 ──
        ["settings.title"] = "{0} 설정",
        ["settings.ok"] = "확인",
        ["settings.cancel"] = "취소",
        ["settings.hint.clean"] = "바꾸는 즉시 배지에 반영됩니다. [확인]을 누르면 저장합니다.",
        ["settings.hint.dirty"] = "저장하지 않은 변경 사항이 있습니다. [취소]하면 되돌립니다.",
        ["toggle.on"] = "켬",
        ["toggle.off"] = "끔",

        // ── 설정 창: 탐색 메뉴와 페이지 ──
        ["nav.appearance"] = "모양",
        ["nav.display"] = "표시",
        ["nav.general"] = "일반",
        ["nav.excluded"] = "제외 앱",
        ["nav.about"] = "정보",
        ["page.appearance.desc"] = "배지의 테마, 모양, 위치, 크기, 색을 고릅니다. 바꾸는 즉시 미리보기와 실제 배지에 반영됩니다.",
        ["page.display.desc"] = "배지를 언제, 어떻게 보여 줄지 정합니다.",
        ["page.general.desc"] = "시작, 단축키, 업데이트, 언어처럼 프로그램 전체에 적용되는 설정입니다.",
        ["page.excluded.desc"] = "원격 데스크톱·가상 머신처럼 안에서 따로 배지를 쓰는 앱에서는 배지를 띄우지 않습니다.",
        ["page.about.desc"] = "버전 정보와 도움이 되는 링크입니다.",

        // ── 모양 페이지 (니모닉: V M L Z O H E) ──
        ["group.preview"] = "미리보기",
        ["preview.collapse"] = "접기",
        ["preview.expand"] = "펼치기",
        ["preview.collapse.name"] = "미리보기 접기",
        ["preview.expand.name"] = "미리보기 펼치기",
        ["preview.tip"] = "왼쪽은 밝은 배경(메모장), 오른쪽은 어두운 배경(VS Code 등)에서의 모습입니다.\n배지가 옆줄 글자를 얼마나 가리는지, 불투명도를 낮추면 얼마나 비치는지도 볼 수 있습니다.",
        ["preview.light"] = "밝은 배경",
        ["preview.dark"] = "어두운 배경",
        ["section.themeShape"] = "테마와 모양",
        ["look.theme"] = "테마(&V)",
        ["look.theme.desc"] = "배지 색과 질감, 이 창의 색을 한 벌로 바꿉니다. 고른 뒤에도 아래에서 배지 색을 따로 바꿀 수 있습니다.",
        ["look.style"] = "배지 모양(&M)",
        ["look.style.desc"] = "기본 모양이나 캐릭터 중에서 고릅니다.",
        ["look.placement"] = "위치(&L)",
        ["look.placement.desc"] = "커서를 기준으로 배지를 놓을 곳입니다. 위쪽은 다음 줄 글자를 덜 가리고, 화면 가장자리라 자리가 없으면 반대쪽으로 옮깁니다. 밑줄 모양은 늘 커서 바로 아래에 붙습니다.",
        ["style.short.box"] = "사각",
        ["style.short.pill"] = "둥근",
        ["style.short.dot"] = "점",
        ["style.short.underline"] = "밑줄",
        ["style.short.dotFlash"] = "점+글자",
        ["place.short.aboveRight"] = "오른쪽 위",
        ["place.short.belowRight"] = "오른쪽 아래",
        ["place.short.aboveLeft"] = "왼쪽 위",
        ["place.short.belowLeft"] = "왼쪽 아래",
        ["place.short.above"] = "위",
        ["place.short.below"] = "아래",
        ["section.sizeColor"] = "크기와 색",
        ["look.size"] = "크기(&Z)",
        ["look.size.desc"] = "모니터 배율(DPI)에 추가로 곱해집니다.",
        ["look.opacity"] = "불투명도(&O)",
        ["look.opacity.desc"] = "배지 배경만 비치고 글자는 또렷하게 유지됩니다.",
        ["look.hangulColor"] = "한글 배지 색(&H)",
        ["look.hangulColor.desc"] = "한글 입력일 때의 배지 색입니다. 글자색(흰색·검은색)은 고른 색의 밝기에 맞춰 자동으로 정해집니다.",
        ["look.englishColor"] = "영문 배지 색(&E)",
        ["look.englishColor.desc"] = "영문 입력일 때의 배지 색입니다.",
        ["look.swatch.tip"] = "견본은 고른 테마에 맞춘 색이고, 마지막 견본은 사용자 지정 색입니다. 글자색은 고른 색의 밝기에 맞춰 자동으로 정해집니다.",
        ["look.highContrastNote"] = "고대비 모드에서는 배지를 시스템 색으로 그립니다. 여기서 고른 색은 고대비를 끄면 쓰입니다.",

        // ── 표시 페이지 (니모닉: B N C S R I F T) ──
        ["look.visibility"] = "배지 표시 방식(&B)",
        ["look.visibility.desc"] = "배지가 옆 글자를 가리는 게 신경 쓰이면 바꿔 보세요. 트레이 아이콘은 늘 상태를 보여 줍니다.",
        ["look.visibility.tip"] = "배지가 옆 글자를 가리는 게 신경 쓰이면 바꿔 보세요. '타이핑 중에는 옅게' 는 글자를 치는 동안 배지를 옅게 했다가 0.8초 멈추면 다시 또렷하게, '한/영이 바뀔 때만 잠깐' 은 한/영·Caps Lock·겹쳐 쓰기가 바뀌거나 다른 입력칸으로 옮겼을 때 2초 동안만 보여 줍니다. 트레이 아이콘은 늘 상태를 보여 줍니다.",
        ["visibility.always"] = "늘 보이기",
        ["visibility.dimWhileTyping"] = "타이핑 중에는 옅게",
        ["visibility.onChange"] = "한/영이 바뀔 때만 잠깐",
        ["look.animate"] = "애니메이션 효과(&N)",
        ["look.animate.desc"] = "나타날 때 서서히, 바뀔 때 살짝 커집니다. Windows 설정의 애니메이션 효과가 꺼져 있으면 생략합니다.",
        ["section.keys"] = "특수 키",
        ["look.capsLock"] = "Caps Lock 표시(&C)",
        ["look.capsLock.desc"] = "Caps Lock 이 켜지면 영문 배지는 a → A, 한글 배지는 한 → 꺆 으로 바뀌고 글자 아래에 밑줄(▁)이 생깁니다. 점·밑줄 모양은 그 아래 가운데에 밑줄이 붙습니다.",
        ["look.capsLock.tip"] = "켜면 영문 배지가 평소 a, Caps Lock 이 켜지면 A 로 바뀌고, 한글 배지는 한 → 꺆 으로 바뀝니다. Caps Lock 이 켜져 있으면 글자 아래에 밑줄도 긋습니다. 글자가 없는 점·밑줄 모양은 점(밑줄) 아래 가운데에 같은 밑줄을 붙입니다. 트레이 아이콘은 그대로입니다. 끄면 항상 한 / A.",
        ["look.shiftHold"] = "Shift 를 누르고 있을 때도 표시(&S)",
        ["look.shiftHold.desc"] = "Shift 를 0.3초 이상 누르고 있으면 지금 입력될 글자를 보여 주고 배지 왼쪽 아래에 ▲ 를 붙입니다(a → A). Caps Lock 표시가 켜져 있어야 합니다.",
        ["look.shiftHold.tip"] = "Shift 를 0.3초 이상 누르고 있으면 떼기 전까지 지금 입력될 글자로 바꿔 보여 줍니다(a → A, 한 → 꺆). ▲ 는 배지 왼쪽 아래 모서리에 그리므로 글자 아래의 Caps Lock 밑줄과 함께 보입니다. Caps Lock 이 켜진 채로 누르면 소문자가 입력되므로 a / 한 과 밑줄, ▲. 점·밑줄 모양은 그 아래 왼쪽에 ▲ 가 붙습니다. 대문자 한 글자를 칠 때처럼 짧게 누르거나 Ctrl·Alt·Win 과 함께 누르면 바뀌지 않습니다(짧게 눌러도 보이게 하려면 아래 '누르는 즉시 표시'). 위의 Caps Lock 표시가 켜져 있어야 동작합니다.",
        ["look.shiftNow"] = "누르는 즉시 표시(&R)",
        ["look.shiftNow.desc"] = "0.3초를 기다리지 않고 Shift 를 누르자마자 보여 줍니다. 대문자 한 글자를 칠 때도 배지가 잠깐 바뀝니다.",
        ["look.shiftNow.tip"] = "끄면(기본) Shift 를 0.3초 이상 누르고 있을 때만 바뀌어, 대문자 한 글자를 칠 때 배지가 깜빡이지 않습니다. 켜면 누르는 즉시(다음 갱신, 기본 0.1초 안에) 바뀌고 떼면 돌아옵니다. 두 갱신 사이에 눌렀다 뗀 아주 짧은 Shift 는 보이지 않을 수 있습니다. Ctrl·Alt·Win 과 함께 누르면 바뀌지 않습니다. 위의 'Shift 를 누르고 있을 때도 표시' 가 켜져 있어야 동작합니다.",
        ["look.insert"] = "Insert(겹쳐 쓰기) 표시(&I)",
        ["look.insert.desc"] = "Insert 를 눌러 겹쳐 쓰기로 바꾼 창에서는 배지 오른쪽 아래에 작은 네모(■)가 붙습니다. 한 번 더 누르면 사라집니다.",
        ["look.insert.tip"] = "겹쳐 쓰기는 앱마다 따로 기억하므로 Insert 를 누른 창에만 ■ 를 보여 주고, 다른 창으로 가면 그 창의 상태를 보여 줍니다. 새로 연 창은 삽입 모드로 봅니다. Ctrl+Insert(복사)·Shift+Insert(붙여넣기)는 세지 않습니다. 브라우저처럼 Insert 로 겹쳐 쓰기를 하지 않는 앱에서 눌러도 ■ 가 생기는데, 한 번 더 누르면 사라집니다. 글자 배지는 오른쪽 아래 모서리, 점·밑줄 모양은 그 아래 오른쪽에 그립니다.",
        ["section.hideTray"] = "숨기기와 트레이",
        ["behavior.fullscreen"] = "전체 화면 앱에서는 숨김(&F)",
        ["behavior.fullscreen.desc"] = "게임이나 동영상을 전체 화면으로 볼 때는 배지를 띄우지 않습니다.",
        ["behavior.trayState"] = "트레이 아이콘에도 한/영 표시(&T)",
        ["behavior.trayState.desc"] = "끄면 트레이 아이콘은 입력 상태와 상관없이 같은 모양으로 보입니다.",

        // ── 일반 페이지 (니모닉: A K U G I P J R) ──
        ["section.startup"] = "시작과 단축키",
        ["behavior.autostart"] = "Windows 로그인 시 자동 시작(&A)",
        ["behavior.autostart.desc"] = "로그인하면 트레이에서 바로 시작합니다. [확인]을 누를 때 적용됩니다.",
        ["behavior.hotkey"] = "일시 중지 단축키(&K)",
        ["behavior.hotkey.desc"] = "어디서든 이 키 조합을 누르면 배지를 잠시 껐다가 다시 켭니다.",
        ["behavior.hotkey.tip"] = "여기를 클릭한 뒤 원하는 키 조합을 누르세요. Ctrl, Alt, Win 중 하나가 들어가야 합니다.",
        ["behavior.hotkey.placeholder"] = "키 조합을 누르세요",
        ["section.updatesLanguage"] = "업데이트와 언어",
        ["behavior.updates"] = "업데이트 알림(&U)",
        ["behavior.updates.desc"] = "하루 한 번 GitHub 에서 새 정식 버전을 확인합니다. 끄면 네트워크에 전혀 접속하지 않습니다.",
        ["behavior.language"] = "언어(&G)",
        ["behavior.language.desc"] = "설정 창·트레이 메뉴·알림의 언어입니다. 배지 글자(한/A)는 바뀌지 않습니다.",
        ["section.advanced"] = "고급",
        ["behavior.poll"] = "확인 주기(&I)",
        ["behavior.poll.desc"] = "한/영 상태를 다시 읽는 간격입니다. 작을수록 빨리 반응하고 CPU 를 조금 더 씁니다. 기본 100ms.",
        ["behavior.poll.tip"] = "한/영 상태를 다시 읽는 간격입니다. 배지가 한동안 안 보이면 자동으로 3배 느려집니다.",
        ["section.manage"] = "설정 관리",
        ["settings.backup"] = "설정 백업",
        ["settings.backup.desc"] = "설정을 파일로 내보내거나 불러와 다른 PC 로 옮깁니다. 가져온 설정은 [확인]을 눌러야 저장됩니다.",
        ["settings.export"] = "내보내기(&P)...",
        ["settings.export.tip"] = "지금 설정 창의 값을 파일로 저장합니다. 다른 PC 에서 '가져오기' 로 불러올 수 있습니다.",
        ["settings.import"] = "가져오기(&J)...",
        ["settings.import.tip"] = "내보낸 설정 파일을 불러와 설정 창에 채웁니다. [확인] 을 눌러야 저장되고, [취소] 하면 원래대로 돌아갑니다.",
        ["settings.fileFilter"] = "ImeBadge 설정 (*.json)|*.json|모든 파일 (*.*)|*.*",
        ["settings.exported"] = "설정을 내보냈습니다",
        ["settings.exportFailed"] = "설정을 내보내지 못했습니다",
        ["settings.imported"] = "설정을 가져왔습니다",
        ["settings.imported.text"] = "설정 창에 채웠습니다. [확인] 을 누르면 저장되고, [취소] 하면 원래 설정으로 돌아갑니다.",
        ["settings.importFailed"] = "설정을 가져오지 못했습니다",
        ["settings.importInvalid"] = "ImeBadge 설정 파일이 아니거나 내용이 손상됐습니다.",
        ["settings.resetTitle"] = "기본값 복원",
        ["settings.resetTitle.desc"] = "고른 테마는 그대로 두고 나머지 설정을 기본값으로 되돌립니다. [취소]를 누르면 원래대로 돌아갑니다.",
        ["settings.reset"] = "복원(&R)",

        // ── 제외 앱 페이지 (니모닉: D) ──
        ["exclude.addTitle"] = "앱 추가",
        ["exclude.addTitle.desc"] = "실행 중인 앱을 고르거나 실행 파일 이름(.exe 생략 가능)을 입력하세요. 끝에 * 를 붙이면 앞부분만 맞으면 됩니다. 예) mstsc, vmware-vmx, Unreal*",
        ["exclude.new.tip"] = "실행 중인 앱을 고르거나 실행 파일 이름을 직접 입력하세요. 끝에 * 를 붙이면 앞부분만 맞으면 됩니다.",
        ["exclude.add"] = "추가(&D)",
        ["exclude.placeholder"] = "실행 파일 이름 (예: mstsc)",
        ["exclude.running"] = "실행 중인 앱에서 고르기 (Alt+↓)",
        ["exclude.listHeader"] = "제외한 앱 ({0})",
        ["exclude.prefix"] = "이름이 {0}(으)로 시작하는 앱",
        ["exclude.removeItem"] = "삭제",
        ["exclude.removeItem.name"] = "{0} 삭제",
        ["exclude.empty"] = "아직 제외한 앱이 없습니다.",

        // ── 실험 기능 페이지 (니모닉: S V K W M C F L) ──
        ["nav.experimental"] = "실험 기능",
        ["page.experimental.desc"] = "아직 다듬는 중인 커서 관련 기능입니다. 모두 처음에는 꺼져 있고, 앱에 따라 잘 맞지 않을 수 있습니다.",
        ["section.exp.caret"] = "커서 찾기",
        ["exp.sonar"] = "커서 소나(&S)",
        ["exp.sonar.desc"] = "단축키를 누르면 원이 커서 자리로 좁혀 들며 지금 어디에 쓰고 있는지 알려 줍니다. 원의 색은 지금 한/영 배지 색입니다.",
        ["exp.sonar.tip"] = "다른 창을 보다 돌아왔을 때, 큰 화면이나 여러 모니터에서 커서를 놓쳤을 때 쓰세요. 배지를 일시 중지한 동안에도 단축키는 동작합니다. 커서를 찾지 못하면 마우스 포인터 옆에 알려 줍니다. Windows 의 애니메이션 효과가 꺼져 있으면 원이 움직이지 않고 잠깐 보였다 사라집니다.",
        ["exp.sonar.preview"] = "보기(&V)",
        ["exp.sonar.preview.tip"] = "이 단추 둘레에서 소나를 한 번 보여 줍니다.",
        ["exp.sonarHotkey"] = "소나 단축키(&K)",
        ["exp.sonarHotkey.desc"] = "어디서든 이 키 조합을 누르면 소나가 커서를 찾아 보여 줍니다.",
        ["exp.sonarOnSwitch"] = "창을 바꾸면 저절로(&W)",
        ["exp.sonarOnSwitch.desc"] = "Alt+Tab 처럼 키보드로 다른 창에 오면 단축키 없이도 한 번 보여 줍니다. 마우스로 창을 고르면 보여 주지 않습니다.",
        ["sonar.notFound"] = "커서를 찾지 못했어요",
        ["sonar.notFound.detail"] = "글자를 입력하는 칸을 클릭한 뒤 다시 눌러 보세요.",
        ["section.exp.typing"] = "입력 도우미",
        ["exp.fieldMemory"] = "입력칸별 한/영 기억(&M)",
        ["exp.fieldMemory.desc"] = "입력칸마다 마지막으로 쓴 한/영을 기억했다가, 다시 들어왔을 때 지금과 다르면 커서 옆에 알려 줍니다. 한/영을 대신 바꾸지는 않습니다.",
        ["exp.fieldMemory.tip"] = "같은 칸에서 글자를 몇 자 치면 그때의 한/영을 기억합니다. 입력칸은 앱 이름과 입력칸 이름으로 알아보고, 그 값을 알아볼 수 없게 바꾼 값(해시)과 한/영만 이 PC 의 설정 폴더(fields.json)에 저장합니다. 입력한 글자는 저장하지 않고, 비밀번호 칸은 기억하지 않습니다. 웹 페이지는 사이트를 구별하지 못해 이름이 같은 입력칸(예: '검색')은 한 칸으로 봅니다.",
        ["exp.fieldMemoryClear"] = "기억한 입력칸",
        ["exp.fieldMemoryClear.desc"] = "{0}개를 기억하고 있습니다. 지우면 처음부터 다시 배웁니다.",
        ["exp.fieldMemoryClear.empty"] = "아직 기억한 입력칸이 없습니다.",
        ["exp.fieldMemoryClear.button"] = "지우기(&C)",
        ["field.hint.hangul"] = "이 칸에서는 보통 한글로 썼어요",
        ["field.hint.hangul.detail"] = "지금은 영문 입력이에요. 한/영 키로 바꿀 수 있어요.",
        ["field.hint.english"] = "이 칸에서는 보통 영문으로 썼어요",
        ["field.hint.english.detail"] = "지금은 한글 입력이에요. 한/영 키로 바꿀 수 있어요.",
        ["exp.focusSteal"] = "포커스 뺏김 경고(&F)",
        ["exp.focusSteal.desc"] = "글자를 치는 도중에 다른 창이 앞으로 튀어나와 입력이 그 창으로 가기 시작하면, 쓰던 자리에 경고를 띄웁니다.",
        ["exp.focusSteal.tip"] = "직전까지 글자를 치고 있었고, 마우스나 Alt·Win·Ctrl 없이 활성 창이 바뀌었고, 바뀐 직후에도 입력이 이어질 때만 알립니다. 입력은 Windows 가 알려 주는 '마지막 입력 시각' 만 보고 어떤 키를 눌렀는지는 읽지 않습니다(키보드 훅 없음). Enter 로 프로그램을 연 뒤 곧바로 치기 시작하면 경고가 뜰 수도 있습니다.",
        ["steal.title"] = "입력이 다른 창으로 가고 있어요",
        ["steal.detail"] = "{0} 창이 앞으로 나왔어요. 쓰던 곳으로 돌아가려면 Alt+Tab 을 누르세요.",
        ["exp.selection"] = "선택 영역 덮어쓰기 표시(&L)",
        ["exp.selection.desc"] = "글을 선택해 둔 입력칸에서는 다음에 치는 글자가 그 글을 지운다는 뜻으로 배지 테두리가 점선(선택 영역 모양)으로 바뀝니다.",
        ["exp.selection.tip"] = "Ctrl+A 로 전체 선택한 것을 잊고 치기 시작해 글이 사라지는 일을 막습니다. 메모장 같은 기본 입력칸, Notepad++, 그리고 크롬·엣지·VS Code 처럼 UI Automation 으로 커서를 찾는 앱에서 동작합니다. 워드·한글처럼 자체 편집기를 쓰는 앱에서는 알 수 없고, 크롬 주소창처럼 선택 범위를 정확히 알려 주지 않는 입력칸에서는 보이지 않을 수 있습니다. 밑줄 모양은 막대가 점선이 됩니다.",

        // ── 정보 페이지 ──
        ["about.update"] = "업데이트",
        ["about.lastCheck"] = "마지막 확인: {0}",
        ["about.neverChecked"] = "아직 확인하지 않았습니다.",
        ["about.checkUpdates"] = "새 버전 확인",
        ["section.links"] = "링크",
        ["about.releases"] = "릴리스(다운로드) 페이지",
        ["about.releases.desc"] = "새 버전을 내려받고 바뀐 점을 볼 수 있습니다.",
        ["about.repo"] = "GitHub 저장소",
        ["about.repo.desc"] = "소스 코드를 보고, 문제를 알리거나 의견을 남길 수 있습니다.",
        ["section.troubleshoot"] = "문제 해결",
        ["about.settingsDir"] = "설정 폴더 열기",
        ["about.settingsDir.desc"] = "설정 파일(settings.json)이 있는 폴더입니다.",
        ["about.logDir"] = "로그 폴더 열기",
        ["about.logDir.desc"] = "문제가 생기면 errors.log 에 원인이 기록됩니다.",
        ["about.copyDiag"] = "진단 정보 복사",
        ["about.copyDiag.desc"] = "버전·Windows·화면 배율 같은 환경 정보를 클립보드에 복사합니다. 이슈를 올릴 때 붙여 넣어 주세요.",
        ["about.copied"] = "클립보드에 복사했습니다.",
        ["about.license"] = "Apache License 2.0 · 개인정보를 수집하지 않습니다",
        ["diag.dpi"] = "DPI: {0} ({1}%), 모니터 {2}대",
        ["diag.theme"] = "테마: {0}{1}, 애니메이션 효과: {2}, UI 언어: {3}",
        ["diag.dark"] = "어둡게",
        ["diag.light"] = "밝게",
        ["diag.highContrast"] = ", 고대비",
        ["diag.on"] = "켜짐",
        ["diag.off"] = "꺼짐",
        ["diag.settings"] = "설정: 모양={0}, 위치={1}, 크기={2}%, 불투명도={3}%, 주기={4}ms, 단축키={5}, 제외 앱={6}개",
        ["diag.experimental"] = "실험 기능: {0}",
        ["diag.none"] = "없음",
        ["diag.exe"] = "실행 파일: {0}",
        ["diag.settingsFile"] = "설정 파일: {0}",
        ["diag.logDir"] = "로그 폴더: {0}",
        ["diag.unknown"] = "(알 수 없음)",

        // ── 대화상자 ──
        ["dialog.details"] = "자세히",
        ["dialog.brief"] = "간단히",
        ["dialog.openLogDir"] = "로그 폴더 열기",
        ["dialog.close"] = "닫기",
        ["dialog.yesPrefix"] = "[예] {0}",
        ["crash.heading"] = "{0}에 문제가 생겨 종료합니다.",
        ["crash.text"] = "자세한 내용은 로그 폴더의 errors.log 에 기록되어 있습니다. 문제가 반복되면 이 파일과 함께 이슈로 알려 주세요.",
        ["hotkey.failed"] = "단축키 {0} 을(를) 등록하지 못했습니다.",
        ["hotkey.failed.text"] = "다른 프로그램이 같은 조합을 쓰고 있을 수 있습니다. 설정에서 다른 조합을 고르세요.",
        ["autostart.failed"] = "자동 시작 설정을 바꾸지 못했습니다.",
        ["autostart.failed.text"] = "로그 폴더의 errors.log 에 원인이 기록되어 있습니다. (트레이 메뉴 → 정보 → 로그 폴더 열기)",

        // ── 업데이트 ──
        ["update.balloon.title"] = "새 버전이 있습니다",
        ["update.balloon.text"] = "{0} {1} 을(를) 받을 수 있습니다. (현재 {2})\n클릭하면 업데이트 창이 열립니다.",
        ["update.none"] = "아직 정식 릴리스가 없습니다.",
        ["update.latest"] = "최신 버전을 쓰고 있습니다.",
        ["update.current"] = "현재 {0}",
        ["update.currentLatest"] = "현재 {0}, 최신 {1}",
        ["update.failed"] = "업데이트 정보를 가져오지 못했습니다.",
        ["update.failed.text"] = "네트워크 연결을 확인한 뒤 다시 시도하세요.",
        ["update.offer.heading"] = "새 버전 {0} 이(가) 있습니다.",
        ["update.offer.text"] = "현재 {0} 을(를) 쓰고 있습니다.",
        ["update.open"] = "다운로드 페이지 열기",
        ["update.open.note"] = "브라우저에서 릴리스 페이지를 엽니다.",
        ["update.later"] = "나중에",
        ["update.later.note"] = "다음에 다시 알립니다.",
        ["update.skip"] = "이 버전 건너뛰기",
        ["update.skip.note"] = "{0} 은(는) 자동으로 알리지 않습니다. 더 새 버전이 나오면 다시 알립니다.",
        ["update.upgrade"] = "지금 업그레이드",
        ["update.upgrade.note"] = "새 버전을 내려받아 적용하고 자동으로 다시 시작합니다.",
        ["update.progress.title"] = "업데이트 {0}",
        ["update.preparing"] = "준비하는 중...",
        ["update.downloading"] = "내려받는 중... {0} / {1} MB",
        ["update.downloading.unknown"] = "내려받는 중... {0} MB",
        ["update.verifying"] = "받은 파일을 확인하는 중...",
        ["update.applying"] = "적용하는 중... 잠시 뒤 새 버전으로 다시 시작합니다.",
        ["update.cancel"] = "취소",
        ["update.auto.failed"] = "자동 업그레이드를 마치지 못했습니다.",
        ["update.auto.failed.text"] = "다운로드 페이지에서 직접 받아 설치할 수 있습니다.",
        ["update.auto.noAsset"] = "이 릴리스에는 지금 쓰는 설치 형태({0})에 맞는 파일이 없습니다.",
        ["update.auto.noChecksum"] = "이 릴리스에 체크섬 목록(SHA256SUMS.txt)이 없어 받은 파일을 확인할 수 없습니다.",
        ["update.auto.checksum"] = "받은 파일이 손상되었습니다(체크섬이 맞지 않음).",
        ["update.apply.failed"] = "새 버전으로 바꾸지 못했습니다.",
        ["update.apply.failed.text"] = "프로그램 파일을 쓸 수 없었습니다. 예전 버전이 그대로 남아 있으니, 다운로드 페이지에서 받아 다시 설치해 주세요.",
    };

    static readonly Dictionary<string, string> En = new()
    {
        // ── App ──
        ["app.name"] = "ImeBadge (Korean/English badge)",
        ["app.tagline"] = "Shows a small badge next to the text caret so you know\nwhether you're typing Korean or English before you type.",
        ["app.firstRun"] = "A Korean/English badge now appears next to the caret. Right-click the tray icon to change its look and behavior.",

        // ── State ──
        ["state.paused"] = "Paused",
        ["state.hangul"] = "Korean",
        ["state.english"] = "English",
        ["state.englishCaps"] = "English (Caps Lock)",
        ["state.hangulCaps"] = "Korean (Caps Lock)",
        ["state.other"] = "Other language",
        ["state.none"] = "No text field",
        ["state.overtype"] = "{0} · Overtype",
        ["tray.resumeWith"] = " · {0} to resume",
        ["tray.pauseWith"] = " · {0} to pause",

        // ── Tray menu (mnemonics: P S H L Z O W U A X) ──
        ["menu.current"] = "Now: {0}",
        ["menu.pause"] = "&Pause",
        ["menu.settings"] = "&Settings...",
        ["menu.theme"] = "&Theme",
        ["menu.style"] = "S&hape",
        ["menu.style.basic"] = "Basic",
        ["menu.style.characters"] = "Characters",
        ["menu.placement"] = "&Location",
        ["menu.size"] = "Si&ze",
        ["menu.opacity"] = "&Opacity",
        ["menu.autostart"] = "Start with &Windows",
        ["menu.checkUpdates"] = "Check for &updates",
        ["menu.about"] = "&About...",
        ["menu.exit"] = "E&xit",
        ["menu.custom"] = "Custom ({0}%)",

        // ── Presets ──
        ["style.box"] = "Square badge",
        ["style.pill"] = "Rounded badge",
        ["style.dot"] = "Dot",
        ["style.underline"] = "Underline",
        ["style.dotFlash"] = "Dot, text for 1.5 s on change",
        ["style.cat"] = "Cat",
        ["style.dog"] = "Dog",
        ["style.heart"] = "Heart",
        ["style.cloud"] = "Cloud",
        ["style.star"] = "Star",
        ["theme.classic"] = "Classic",
        ["theme.blossom"] = "Blossom",
        ["theme.candy"] = "Candy",
        ["theme.mint"] = "Mint Choco",
        ["theme.midnight"] = "Midnight",
        ["place.aboveRight"] = "Above right of caret",
        ["place.belowRight"] = "Below right of caret",
        ["place.aboveLeft"] = "Above left of caret",
        ["place.belowLeft"] = "Below left of caret",
        ["place.above"] = "Above caret",
        ["place.below"] = "Below caret",
        ["size.small"] = "Small (80%)",
        ["size.normal"] = "Normal (100%)",
        ["size.large"] = "Large (130%)",
        ["size.xlarge"] = "Extra large (160%)",
        ["opacity.100"] = "Opaque (100%)",
        ["opacity.85"] = "Slightly see-through (85%)",
        ["opacity.70"] = "Translucent (70%)",
        ["opacity.50"] = "Mostly see-through (50%)",
        ["language.auto"] = "System language (auto)",
        ["language.ko"] = "한국어",
        ["language.en"] = "English",

        // ── Settings window ──
        ["settings.title"] = "{0} Settings",
        ["settings.ok"] = "OK",
        ["settings.cancel"] = "Cancel",
        ["settings.hint.clean"] = "Changes apply to the badge right away. Press OK to save them.",
        ["settings.hint.dirty"] = "You have unsaved changes. Cancel undoes them.",
        ["toggle.on"] = "On",
        ["toggle.off"] = "Off",

        // ── Settings window: navigation and pages ──
        ["nav.appearance"] = "Appearance",
        ["nav.display"] = "Display",
        ["nav.general"] = "General",
        ["nav.excluded"] = "Excluded apps",
        ["nav.about"] = "About",
        ["page.appearance.desc"] = "Choose the badge's theme, shape, position, size and colors. Changes show up in the preview and on the real badge right away.",
        ["page.display.desc"] = "Decide when and how the badge is shown.",
        ["page.general.desc"] = "Settings for the whole app, such as startup, hotkey, updates and language.",
        ["page.excluded.desc"] = "The badge stays hidden in these apps, such as Remote Desktop or virtual machines that show their own badge inside.",
        ["page.about.desc"] = "Version information and helpful links.",

        // ── Appearance page (mnemonics: V S L Z O K E) ──
        ["group.preview"] = "Preview",
        ["preview.collapse"] = "Collapse",
        ["preview.expand"] = "Expand",
        ["preview.collapse.name"] = "Collapse preview",
        ["preview.expand.name"] = "Expand preview",
        ["preview.tip"] = "Left: on a light background (Notepad). Right: on a dark background (VS Code etc.).\nIt also shows how much of the neighboring line the badge covers, and how much shows through at lower opacity.",
        ["preview.light"] = "Light background",
        ["preview.dark"] = "Dark background",
        ["section.themeShape"] = "Theme and shape",
        ["look.theme"] = "&Visual theme",
        ["look.theme.desc"] = "Changes the badge colors, finish and this window's colors as a set. You can still pick badge colors below afterwards.",
        ["look.style"] = "Badge &shape",
        ["look.style.desc"] = "Pick a basic shape or a character.",
        ["look.placement"] = "&Location",
        ["look.placement.desc"] = "Where the badge sits relative to the caret. Above hides less of the next line; if there is no room at the screen edge, the badge moves to the other side. The Underline shape always sits right under the caret.",
        ["style.short.box"] = "Square",
        ["style.short.pill"] = "Rounded",
        ["style.short.dot"] = "Dot",
        ["style.short.underline"] = "Underline",
        ["style.short.dotFlash"] = "Dot+text",
        ["place.short.aboveRight"] = "Above right",
        ["place.short.belowRight"] = "Below right",
        ["place.short.aboveLeft"] = "Above left",
        ["place.short.belowLeft"] = "Below left",
        ["place.short.above"] = "Above",
        ["place.short.below"] = "Below",
        ["section.sizeColor"] = "Size and color",
        ["look.size"] = "Si&ze",
        ["look.size.desc"] = "Multiplied on top of the monitor's DPI scaling.",
        ["look.opacity"] = "&Opacity",
        ["look.opacity.desc"] = "Only the badge background becomes see-through; the text stays crisp.",
        ["look.hangulColor"] = "&Korean badge color",
        ["look.hangulColor.desc"] = "Badge color while typing Korean. The text color (white or black) follows the brightness of the color you pick.",
        ["look.englishColor"] = "&English badge color",
        ["look.englishColor.desc"] = "Badge color while typing English.",
        ["look.swatch.tip"] = "The swatches match the chosen theme; the last one is a custom color. The text color follows the brightness of the color you pick.",
        ["look.highContrastNote"] = "In high contrast mode the badge uses system colors. The colors picked here apply when high contrast is off.",

        // ── Display page (mnemonics: B N C A R I F T) ──
        ["look.visibility"] = "&Badge display",
        ["look.visibility.desc"] = "Try this if the badge covers text next to it. The tray icon always shows the mode.",
        ["look.visibility.tip"] = "Try this if the badge covers text next to it. 'Fade while typing' dims the badge while you type and brings it back after a 0.8 s pause. 'Only briefly on change' shows it for 2 s when Korean/English, Caps Lock or overtype changes or you move to another input box. The tray icon always shows the mode.",
        ["visibility.always"] = "Always",
        ["visibility.dimWhileTyping"] = "Fade while typing",
        ["visibility.onChange"] = "Only briefly on change",
        ["look.animate"] = "A&nimation",
        ["look.animate.desc"] = "Fades in when shown and pulses when the mode changes. Skipped when Windows animation effects are off.",
        ["section.keys"] = "Special keys",
        ["look.capsLock"] = "Show &Caps Lock",
        ["look.capsLock.desc"] = "With Caps Lock on, the English badge changes from a to A and the Korean badge from 한 to 꺆, with a bar (▁) under the letter. The dot and underline shapes get the bar below them, in the middle.",
        ["look.capsLock.tip"] = "When on, the English badge reads a normally and A with Caps Lock on; the Korean badge changes from 한 to 꺆. With Caps Lock on, a bar is drawn under the letter as well. The dot and underline shapes have no letter, so the same bar appears below them, in the middle. The tray icon stays the same. When off, always 한 / A.",
        ["look.shiftHold"] = "&Also show Shift while it is held",
        ["look.shiftHold.desc"] = "While Shift is held for 0.3 s or longer, the badge shows the letter you would type now with a ▲ at its lower left (a → A). Requires Show Caps Lock.",
        ["look.shiftHold.tip"] = "While Shift is held for 0.3 s or longer, the badge shows the letter you would type now (a → A, 한 → 꺆). The ▲ sits at the lower-left corner, so it appears together with the Caps Lock bar under the letter. With Caps Lock on, holding Shift types lowercase, so the badge shows a / 한 with the bar and ▲. The dot and underline shapes show the ▲ below them, on the left. A quick Shift for a single capital letter, or Shift together with Ctrl, Alt or Win, does not change the badge (turn on 'Show right away' below to see quick presses too). Requires Show Caps Lock above.",
        ["look.shiftNow"] = "Show &right away",
        ["look.shiftNow.desc"] = "Shows Shift as soon as it is pressed, without waiting 0.3 s. The badge also changes briefly when you type a single capital letter.",
        ["look.shiftNow.tip"] = "When off (default), the badge changes only after Shift is held for 0.3 s, so typing a single capital letter does not make it flicker. When on, it changes as soon as Shift is pressed (at the next update, within 0.1 s by default) and changes back on release. A very quick tap between two updates may not show. Shift together with Ctrl, Alt or Win does not change the badge. Requires 'Also show Shift while it is held' above.",
        ["look.insert"] = "Show &Insert (overtype)",
        ["look.insert.desc"] = "After you press Insert to switch a window to overtype, the badge gets a small square (■) at its lower right. Press Insert again to remove it.",
        ["look.insert.tip"] = "Each app remembers overtype on its own, so the ■ appears only in the window where you pressed Insert; other windows show their own state, and newly opened windows count as insert mode. Ctrl+Insert (copy) and Shift+Insert (paste) are not counted. Apps that ignore Insert, such as web browsers, still get the ■ when you press it; press Insert again to clear it. Letter badges show it at the lower-right corner; the dot and underline shapes show it below them, on the right.",
        ["section.hideTray"] = "Hiding and tray",
        ["behavior.fullscreen"] = "Hide in &fullscreen apps",
        ["behavior.fullscreen.desc"] = "The badge stays hidden while a game or video plays full screen.",
        ["behavior.trayState"] = "Show the mode on the &tray icon",
        ["behavior.trayState.desc"] = "When off, the tray icon looks the same whatever the input mode.",

        // ── General page (mnemonics: W H U G I X P R) ──
        ["section.startup"] = "Startup and hotkey",
        ["behavior.autostart"] = "Start with &Windows",
        ["behavior.autostart.desc"] = "Starts in the tray when you sign in. Applied when you press OK.",
        ["behavior.hotkey"] = "Pause &hotkey",
        ["behavior.hotkey.desc"] = "Press this key combination anywhere to pause or resume the badge.",
        ["behavior.hotkey.tip"] = "Click here, then press the key combination you want. It must include Ctrl, Alt or Win.",
        ["behavior.hotkey.placeholder"] = "Press a key combination",
        ["section.updatesLanguage"] = "Updates and language",
        ["behavior.updates"] = "&Update notifications",
        ["behavior.updates.desc"] = "Checks GitHub for a new stable release once a day. When off, the app never touches the network.",
        ["behavior.language"] = "Lan&guage",
        ["behavior.language.desc"] = "Language of the settings window, tray menu and notifications. The badge text (한/A) does not change.",
        ["section.advanced"] = "Advanced",
        ["behavior.poll"] = "Poll &interval",
        ["behavior.poll.desc"] = "How often the mode is re-read. Lower reacts faster and uses a bit more CPU. Default 100 ms.",
        ["behavior.poll.tip"] = "How often the mode is re-read. Slows down 3× automatically while the badge has been hidden for a while.",
        ["section.manage"] = "Manage settings",
        ["settings.backup"] = "Back up settings",
        ["settings.backup.desc"] = "Export your settings to a file, or import them to move them to another PC. Imported settings are saved when you press OK.",
        ["settings.export"] = "E&xport...",
        ["settings.export.tip"] = "Save the values in this window to a file. Load it on another PC with Import.",
        ["settings.import"] = "Im&port...",
        ["settings.import.tip"] = "Load an exported settings file into this window. Press OK to save it, or Cancel to go back.",
        ["settings.fileFilter"] = "ImeBadge settings (*.json)|*.json|All files (*.*)|*.*",
        ["settings.exported"] = "Settings exported",
        ["settings.exportFailed"] = "Could not export settings",
        ["settings.imported"] = "Settings imported",
        ["settings.imported.text"] = "They are filled into this window. Press OK to save them, or Cancel to go back to your previous settings.",
        ["settings.importFailed"] = "Could not import settings",
        ["settings.importInvalid"] = "This is not an ImeBadge settings file, or it is damaged.",
        ["settings.resetTitle"] = "Reset to defaults",
        ["settings.resetTitle.desc"] = "Keeps the chosen theme and resets everything else. Press Cancel to undo.",
        ["settings.reset"] = "&Reset",

        // ── Excluded apps page (mnemonics: D) ──
        ["exclude.addTitle"] = "Add an app",
        ["exclude.addTitle.desc"] = "Pick a running app or type an executable name (.exe optional). A trailing * matches by prefix. e.g. mstsc, vmware-vmx, Unreal*",
        ["exclude.new.tip"] = "Pick a running app or type an executable name. A trailing * matches by prefix.",
        ["exclude.add"] = "A&dd",
        ["exclude.placeholder"] = "Executable name (e.g. mstsc)",
        ["exclude.running"] = "Pick from running apps (Alt+↓)",
        ["exclude.listHeader"] = "Excluded apps ({0})",
        ["exclude.prefix"] = "Apps whose name starts with {0}",
        ["exclude.removeItem"] = "Remove",
        ["exclude.removeItem.name"] = "Remove {0}",
        ["exclude.empty"] = "No apps are excluded yet.",

        // ── Experimental page (mnemonics: S V K W M C F L) ──
        ["nav.experimental"] = "Experimental",
        ["page.experimental.desc"] = "Caret features that are still being polished. They are all off at first and may not work well in every app.",
        ["section.exp.caret"] = "Finding the caret",
        ["exp.sonar"] = "Caret &sonar",
        ["exp.sonar.desc"] = "Press the hotkey and rings close in on the caret to show where you are typing. The rings use the current Korean/English badge color.",
        ["exp.sonar.tip"] = "Useful when you come back from another window or lose the caret on a large screen or across monitors. The hotkey works even while the badge is paused. If no caret is found, a note appears next to the mouse pointer. When Windows animation effects are off, the rings do not move; they appear briefly and disappear.",
        ["exp.sonar.preview"] = "Pre&view",
        ["exp.sonar.preview.tip"] = "Plays the sonar once around this button.",
        ["exp.sonarHotkey"] = "Sonar hot&key",
        ["exp.sonarHotkey.desc"] = "Press this key combination anywhere to find the caret with the sonar.",
        ["exp.sonarOnSwitch"] = "Play when you s&witch windows",
        ["exp.sonarOnSwitch.desc"] = "Plays once, without the hotkey, when you move to another window with the keyboard, such as Alt+Tab. It does not play when you pick a window with the mouse.",
        ["sonar.notFound"] = "Caret not found",
        ["sonar.notFound.detail"] = "Click a text field, then press the hotkey again.",
        ["section.exp.typing"] = "Typing helpers",
        ["exp.fieldMemory"] = "Re&member Korean/English per field",
        ["exp.fieldMemory.desc"] = "Remembers the input mode you last used in each text field. When you come back and the mode differs, a note appears next to the caret. It never switches the mode for you.",
        ["exp.fieldMemory.tip"] = "The mode is remembered after you type a few characters in a field. Fields are recognized by app name and field name; only an unreadable hash of those plus Korean/English is stored in the settings folder on this PC (fields.json). What you type is never stored, and password fields are not remembered. Web pages are not told apart by site, so fields with the same name (for example 'Search') count as one.",
        ["exp.fieldMemoryClear"] = "Remembered fields",
        ["exp.fieldMemoryClear.desc"] = "{0} fields remembered. Clearing them starts learning from scratch.",
        ["exp.fieldMemoryClear.empty"] = "No fields remembered yet.",
        ["exp.fieldMemoryClear.button"] = "&Clear",
        ["field.hint.hangul"] = "You usually type Korean here",
        ["field.hint.hangul.detail"] = "Input is English now. Press the Korean/English key to switch.",
        ["field.hint.english"] = "You usually type English here",
        ["field.hint.english.detail"] = "Input is Korean now. Press the Korean/English key to switch.",
        ["exp.focusSteal"] = "&Focus-steal warning",
        ["exp.focusSteal.desc"] = "If another window jumps to the front while you are typing and starts receiving your keystrokes, a warning appears where you were typing.",
        ["exp.focusSteal.tip"] = "It warns only when you were typing just before, the active window changed without the mouse or Alt, Win or Ctrl, and input kept coming right after the change. Only the 'last input time' that Windows reports is used; which keys you press is never read (no keyboard hook). Opening a program with Enter and typing right away may also show the warning.",
        ["steal.title"] = "Your typing is going to another window",
        ["steal.detail"] = "{0} came to the front. Press Alt+Tab to go back.",
        ["exp.selection"] = "Show se&lection overwrite",
        ["exp.selection.desc"] = "When text is selected in the field, the badge border turns into a dashed line (the selection look) because the next key you type will replace that text.",
        ["exp.selection.tip"] = "Helps you avoid typing over everything after a forgotten Ctrl+A. Works in standard text fields such as Notepad, in Notepad++, and in apps where the caret is found through UI Automation, such as Chrome, Edge and VS Code. Apps with their own editors, such as Word or Hangul, cannot report it, and fields that do not report the selection correctly, such as the Chrome address bar, may not show it. The underline shape turns dashed.",

        // ── About page ──
        ["about.update"] = "Updates",
        ["about.lastCheck"] = "Last checked: {0}",
        ["about.neverChecked"] = "Not checked yet.",
        ["about.checkUpdates"] = "Check for updates",
        ["section.links"] = "Links",
        ["about.releases"] = "Releases (downloads)",
        ["about.releases.desc"] = "Download new versions and see what changed.",
        ["about.repo"] = "GitHub repository",
        ["about.repo.desc"] = "Browse the source code, report problems or leave feedback.",
        ["section.troubleshoot"] = "Troubleshooting",
        ["about.settingsDir"] = "Open settings folder",
        ["about.settingsDir.desc"] = "The folder that holds the settings file (settings.json).",
        ["about.logDir"] = "Open log folder",
        ["about.logDir.desc"] = "When something goes wrong, the cause is recorded in errors.log.",
        ["about.copyDiag"] = "Copy diagnostics",
        ["about.copyDiag.desc"] = "Copies your version, Windows and display scaling details to the clipboard. Paste them into an issue.",
        ["about.copied"] = "Copied to the clipboard.",
        ["about.license"] = "Apache License 2.0 · No personal data is collected",
        ["diag.dpi"] = "DPI: {0} ({1}%), {2} monitor(s)",
        ["diag.theme"] = "Theme: {0}{1}, animation effects: {2}, UI language: {3}",
        ["diag.dark"] = "dark",
        ["diag.light"] = "light",
        ["diag.highContrast"] = ", high contrast",
        ["diag.on"] = "on",
        ["diag.off"] = "off",
        ["diag.settings"] = "Settings: shape={0}, placement={1}, size={2}%, opacity={3}%, interval={4}ms, hotkey={5}, excluded apps={6}",
        ["diag.experimental"] = "Experimental: {0}",
        ["diag.none"] = "none",
        ["diag.exe"] = "Executable: {0}",
        ["diag.settingsFile"] = "Settings file: {0}",
        ["diag.logDir"] = "Log folder: {0}",
        ["diag.unknown"] = "(unknown)",

        // ── Dialogs ──
        ["dialog.details"] = "Details",
        ["dialog.brief"] = "Less",
        ["dialog.openLogDir"] = "Open log folder",
        ["dialog.close"] = "Close",
        ["dialog.yesPrefix"] = "[Yes] {0}",
        ["crash.heading"] = "{0} ran into a problem and has to close.",
        ["crash.text"] = "Details are in errors.log in the log folder. If this keeps happening, please open an issue and attach that file.",
        ["hotkey.failed"] = "Could not register the hotkey {0}.",
        ["hotkey.failed.text"] = "Another program may be using the same combination. Pick a different one in Settings.",
        ["autostart.failed"] = "Could not change the startup setting.",
        ["autostart.failed.text"] = "The cause is recorded in errors.log in the log folder (tray menu → About → Open log folder).",

        // ── Updates ──
        ["update.balloon.title"] = "New version available",
        ["update.balloon.text"] = "{0} {1} is available (you have {2}).\nClick to open the update window.",
        ["update.none"] = "There is no stable release yet.",
        ["update.latest"] = "You're on the latest version.",
        ["update.current"] = "Current: {0}",
        ["update.currentLatest"] = "Current {0}, latest {1}",
        ["update.failed"] = "Could not fetch update information.",
        ["update.failed.text"] = "Check your network connection and try again.",
        ["update.offer.heading"] = "Version {0} is available.",
        ["update.offer.text"] = "You are using {0}.",
        ["update.open"] = "Open download page",
        ["update.open.note"] = "Opens the release page in your browser.",
        ["update.later"] = "Later",
        ["update.later.note"] = "Remind me next time.",
        ["update.skip"] = "Skip this version",
        ["update.skip.note"] = "{0} won't be announced again. You'll be notified when a newer version is out.",
        ["update.upgrade"] = "Upgrade now",
        ["update.upgrade.note"] = "Downloads the new version, applies it and restarts automatically.",
        ["update.progress.title"] = "Update {0}",
        ["update.preparing"] = "Preparing...",
        ["update.downloading"] = "Downloading... {0} / {1} MB",
        ["update.downloading.unknown"] = "Downloading... {0} MB",
        ["update.verifying"] = "Verifying the download...",
        ["update.applying"] = "Applying... the new version will start in a moment.",
        ["update.cancel"] = "Cancel",
        ["update.auto.failed"] = "The automatic upgrade could not be completed.",
        ["update.auto.failed.text"] = "You can download and install the new version yourself.",
        ["update.auto.noAsset"] = "This release has no file for the way this copy was installed ({0}).",
        ["update.auto.noChecksum"] = "This release has no checksum list (SHA256SUMS.txt), so the download cannot be verified.",
        ["update.auto.checksum"] = "The downloaded file is corrupt (checksum mismatch).",
        ["update.apply.failed"] = "Could not switch to the new version.",
        ["update.apply.failed.text"] = "The program file could not be written. Your current version is untouched - please download and install the new version manually.",
    };
}
